site:
  title: "Asish Panda"
  subtitle: "Generalist"
  description: "I seek to arrive at the right question to ask."
  author: "Asish Panda"
  email: "me@asishpanda.dev"
  
  # Social links
  links:
    twitter: "https://twitter.com/thestillpanda"
  
  # Site settings
  base_url: "http://localhost:8000"
  output_dir: "output"
  
# Navigation items
navigation:
  - name: "Home"
    id: "home"
    active: true
  - name: "Writings"
    id: "writings"
    active: false
  # Temporarily hidden projects navigation - uncomment to restore
  # - name: "Projects"
  #   id: "projects"
  #   active: false

# Content metadata is now automatically read from markdown files in content/
# No manual configuration needed - just add markdown files with frontmatter