site:
  title: "Asish Panda"
  subtitle: "Generalist"
  description: "I seek to arrive at the right question to ask."
  author: "Asish Panda"
  email: "me@asishpanda.dev"
  
  # Social links
  links:
    twitter: "https://twitter.com/thestillpanda"
  
  # Site settings
  base_url: "https://asishpanda.dev"
  output_dir: "output"
  
# Navigation items
navigation:
  - name: "Writings"
    id: "writings"
  - name: "Projects"
    id: "projects"

# Content metadata is now automatically read from markdown files in content/
# No manual configuration needed - just add markdown files with frontmatter

# Pagination configuration
pagination:
  items_per_page: 10          # Number of items to show per page
  show_page_numbers: true     # Whether to show numbered pagination
  max_page_links: 5           # Maximum number of page links to show in navigation
  compact_cards: true         # Use compact card design globally